---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-project
  template:
    metadata:
      labels:
        app: insurance-project
    spec:
      containers:
        - name: insurance
          image: king094/insurance-project:v1.0.0.0
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"

apiVersion: v1
kind: Service
metadata:
  name: insurance-project
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 8081  
  selector:
    app: insurance-project

